mps: 100000
max_backlog: 1000000
logging_level: "info"
logging_type: "text"
metrics_port: 2112
profiling_port: 8081
db:
  port: 5432
  host: "localhost"
  name: "tasks"
  username: "username"
  password: "password"
  ssl_mode: "disable"
  pool_size: 45
grpc:
  port: 3333
  host: "localhost"