global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "producer"
    static_configs:
      - targets: ['host.docker.internal:2112']
  - job_name: "consumer"
    static_configs:
      - targets: ['host.docker.internal:2113']