{
 "title": "Tasks",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Consumption Rate",
   "type": "timeseries",
   "description": "tracks consumption rate",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(task_total_received[1m])", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Production Rate",
   "type": "timeseries",
   "description": "producer rate",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 0 },
   "targets": [
    { "expr": "rate(total_produced[1m])", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Total Produced",
   "type": "gauge",
   "description": "total count of produced tasks",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_produced", "legendFormat": "{{total_produced}}" }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "description": "counts connections to the db",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(numbackends) FROM pg_stat_database;"
    }
   ]
  },
  {
   "title": "Up & Reachable",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Total Value Count",
   "type": "barchart",
   "description": "counts total value of produced tasks categorized by task type",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "targets": [
    { "expr": "task_total_value_per_task_type", "legendFormat": "{{task_type}}" }
   ]
  },
  {
   "title": "Total Task Count",
   "type": "barchart",
   "description": "total count of produced tasks categorized by task type",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 9 },
   "targets": [
    { "expr": "task_total_per_task_type", "legendFormat": "{{task_type}}" }
   ]
  },
  {
   "title": "Task State Counter",
   "type": "gauge",
   "description": "Tracks number of tasks in each state",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "task_count_per_state", "legendFormat": "{{task_state}}" }
   ]
  }
 ]
}