// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

type Task struct {
	ID             int32
	Type           int32
	Value          int32
	State          string
	CreationTime   float64
	LastUpdateTime float64
}
