apiVersion: 1
datasources:
  - name: postgres
    type: postgres
    access: proxy
    orgId: 1
    uid: grafana-postgresql-datasource
    url: postgres:5432
    user: username
    secureJsonData:
      password: 'password'
    jsonData:
      database: tasks
      sslmode: disable # disable/require/verify-ca/verify-full
      maxOpenConns: 500 # Grafana v5.4+
      maxIdleConns: 500 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 1500 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false
    version: 2
    editable: true